# Generated by Django 5.0 on 2025-07-05 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_badge_badgeassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['threshold', 'name']},
        ),
        migrations.AlterModelOptions(
            name='badgeassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AddField(
            model_name='badge',
            name='active',
            field=models.BooleanField(default=True, help_text='Disponible o Próximamente'),
        ),
        migrations.AddField(
            model_name='badge',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Descuento (%) futuro'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(help_text='SVG/PNG para mostrar', upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='Ej. Starter, Partner, CO₂ Helper', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='threshold',
            field=models.PositiveIntegerField(default=0, help_text='Recetas IA o shares necesarios'),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(help_text='Canal, p.e. whatsapp, twitter…', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
