# Generated by Django 5.0 on 2025-07-05 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_badge_options_alter_badgeassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(help_text='SVG o PNG', upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='Ej. Starter, Eco-Hero, Partner', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='threshold',
            field=models.PositiveIntegerField(default=0, help_text='Umbral de recetas o shares'),
        ),
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
