# Generated by Django 5.0 on 2025-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_badge_discount_alter_badge_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={},
        ),
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Descripción de la insignia y beneficio que otorga'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='active',
            field=models.BooleanField(default=True, help_text='Si ya está disponible o aparece como Próximamente'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Descuento (%) que ofrece esta insignia cuando esté activa'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(help_text='SVG o PNG para mostrar en la UI', upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='Ej. Starter, Eco-Hero', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='threshold',
            field=models.PositiveIntegerField(default=0, help_text='Número de acciones necesarias para desbloquear'),
        ),
    ]
