# Generated by Django 5.0 on 2025-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_badge_options_badge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='metric',
            field=models.CharField(choices=[('recipes', 'Recetas IA'), ('shares', 'Compartidos')], default='recipes', help_text='Tipo de métrica para esta insignia', max_length=10),
        ),
    ]
