# Generated by Django 5.0 on 2025-07-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_badge_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='icon',
        ),
    ]
