# Generated by Django 5.0 on 2025-07-06 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Descripción de la insignia y beneficio que otorga'),
        ),
    ]
